--- 
title: "Digital Humanities in Middle Eastern Studies"
author: "Maxim G. Romanov"
date: "`r Sys.Date()`"
description: "This is a collection of relevant materials for the class '57-525 S: Digital Humanities in Middle East Studies --- Introduction to Algorithmic Analysis' (WS2021), offered at the University of Hamburg (Afrika-Asien Institut) and taught by Maxim G. Romanov"
url: 'https\://maximromanov.github.io/dh_in_mes/'
github-repo: "maximromanov/dh_in_mes"
apple-touch-icon: "touch-icon.png"
apple-touch-icon-size: 120
favicon: "favicon.ico"
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
---

# Syllabus{-}

## Course Details{-}

* Course: 57-525 S: Digital Humanities in Middle East Studies --- `Introduction to Algorithmic Analysis` (WS2021)
* Language of instruction: English
* Meeting time: Mo 12:00-14:00
* Meeting place: due to COVID, all meetings will be held online via Zoom
* Meeting link: *shared via Slack*; other details are available via STiNE
* Office hours: Mo 14:00-15:00 (on Zoom); if you have any questions, please, post them on Slack
* Instructor: Dr. Maxim Romanov, [maxim.romanov@uni-hamburg.de](maxim.romanov@uni-hamburg.de)
* Course: 070172-1 UE Methodological course - Introduction to DH: Tools & Techniques (2020W) `Memex Edition`
* Instructor: Dr. Maxim Romanov, [maxim.romanov@univie.ac.at](maxim.romanov@univie.ac.at)


## Aims, contents and method of the course

The course is a practical introduction to a series of digital tools and techniques that are relevant for analytical work both inside and outside of academia. The course will cover such topics as sustainable academic/analytical writing, organization of research workflow, data collection and structuring, as well as basics of text analysis, mapping, and social network analysis. In the course of these units, you will start working with Python, one of the most prominent programming languages used now by humanists and data scientists alike (no prior programming experience is required, but beneficial). The assessment will be based on your in-class participation, timely submission of homework assignments, and the final project, where you will be encouraged to work with data from your disciplinary domain.

Personal computers are required both for in-class work and for your homework (running full versions of either Windows, MacOS, or Linux; unfortunately, neither tablets nor Chrome-based laptops are suitable for this course).

## Course Evaluation 

Course evaluation will be a combination of in-class participation (30%), weekly homework assignments (50%), and the final project (20%). 

## Class Participation

Each class session will consist in large part of practical hands-on exercises led by the instructor. BRING YOUR LAPTOP! We will accommodate whatever operating system you use (Windows, Mac, Linux), but it should be a laptop rather than a tablet. Don’t forget that asking for help counts as participation!

## Homework

Just as in research and real life, collaboration is a very good way to learn and is therefore encouraged. If you need help with any assignment, you are welcome to ask a fellow student. If you do work together on homework assignments, then when you submit it please include a brief note (just a sentence or two) to indicate who did what.

**NB:** On submitting homework, see below.

## Final Project

Final project will be discussed later. You will have an option to build on what we will be doing in class, but you are most encouraged to pick a topic of your own. The best option will be to work on something relevant to your field of study, your term paper or your thesis.

## Study materials:

Most study materials will be distributed by the instructor.
* Zelle, John M. 2016. *Python Programming: An Introduction to Computer Science*. 3rd edition. Portland, Oregon: FRANKLIN BEEDLE & ASSOC.
* “Programming Historian” offers a number of tutorials for aspiring digital humanists. These will be assigned to you as reference materials. You also are encouraged to explore those tutorials that are not included into the course. <https://programminghistorian.org/lessons/>
* Paul Vierthaler's “Hacking the Humanities Tutorials” (Python), <https://www.youtube.com/playlist?list=PL6kqrM2i6BPIpEF5yHPNkYhjHm-FYWh17>

## Software, Tools, & Technologies:

The following is the list of software, applications and packages that we will be using in the course. Make sure to have them installed by the class when we are supposed to use them.

* Zotero, <https://www.zotero.org/>;
* MS Word or Apache OpenOffice (you most likely already have one of these)
* [Mac] Terminal / [Windows] Powershell (both are already on your machines)
* Python <https://www.python.org/>
* git and <https://github.com/>, version control system 
* pandoc (<https://pandoc.org/>), markdown, bibTeX (bibliographical format for LaTeX)
* QGIS, a Free and Open Source Geographic Information System (<https://qgis.org/en/site/>)
* Regular expressions, EditPad Pro/Sublime Text
* Wget (<https://www.gnu.org/software/wget/>), a free software package for retrieving files
* [TEI] XML, csv/tsv, json, yml, etc.
* Gephi (<https://gephi.org/>)

## Submitting Homework:

* Homework assignments are to be submitted by the beginning of the next class;
* For the first few classes you must email them to the instructor (as attachments)
* Later, you will be publishing your homework assignments on your github pages and sending an email to the instructor informing that you have completed your homework and providing a relevant github link.
	*  In the subject of your email, please, use the following format: `CourseID-LessonID-HW-Lastname-matriculationNumber`, for example, if I were to submit homework for the first lesson, my subject header would look like: `070112-L01-HW-Romanov-12435687`.
* DH is a collaborative field, so you are most welcome to work on your homework assignments in groups, however, you must still submit it. That is, if a groups of three works on one assignment, there must be three separate submissions: either emailed from each member’s email and published at each member’s github page.  

## Schedule

**Location**: Online

* 01 - Mo, 11. Okt. 2021 - 12:00-14:00
* 02 - Mo, 18. Okt. 2021 - 12:00-14:00
* 03 - Mo, 25. Okt. 2021 - 12:00-14:00
* 04 - Mo, 01. Nov. 2021 - 12:00-14:00
* 05 - Mo, 08. Nov. 2021 - 12:00-14:00
* 06 - Mo, 15. Nov. 2021 - 12:00-14:00
* 07 - Mo, 22. Nov. 2021 - 12:00-14:00
* 08 - Mo, 29. Nov. 2021 - 12:00-14:00
* 09 - Mo, 06. Dez. 2021 - 12:00-14:00
* 10 - Mo, 13. Dez. 2021 - 12:00-14:00
* 11 - Mo, 03. Jan. 2022 - 12:00-14:00
* 12 - Mo, 10. Jan. 2022 - 12:00-14:00
* 13 - Mo, 17. Jan. 2022 - 12:00-14:00
* 14 - Mo, 24. Jan. 2022 - 12:00-14:00

## Lesson Topics (subject to modification)

- **[ #01 ]** Citation Management and Academic Writing I - with Zotero and MS Word or Open Office
- **[ #02 ]** “Off with the Interface!” Getting to know the command line
- **[ #03 ]** Version Control and Collaboration: Github.com
- **[ #04 ]** Citation Management and Academic Writing II - with Pandoc, markdown, Zotero/BibTex
- **[ #05 ]** Constructing robust searches with Regular expressions
- **[ #06 ]** Webscraping with Wget, preparing URLs with Python and other tools // “The Dispatch”
- ~~**[ #07 ]** Text Markup [TEI XML], and how to remove it... - with Python scripts [anaconda]~~
- **[ #07 ]** Understanding Structured Data
- **[ #08 ]** Converting data into different formats // “The Dispatch”
- ~~**[ #09 ]** Georeferencing with QGIS~~
- **[ #09 ]** Extracting tagged data for analysis // “The Dispatch”
- ~~**[ #10 ]** Text to Map (1/2) - with Python and QGIS~~
- **[ #10 ]** Graphing chronological data  // “The Dispatch”
- ~~**[ #11 ]** Text to Map (2/2) - with Python and QGIS~~
- **[ #11 ]** Mapping data // “The Dispatch”
- **[ #12 ]** Topic modeling & TF-IDF // “The Dispatch”
- **[ #13 ]** Social Network Analysis (with Gephi); modeling network data // “The Dispatch”

